@startuml context-view
!include <C4/C4_Context.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/confluence>
!include <tupadr3/font-awesome-5/jira>







title Context View of the Project Management Systems
Boundary(mybank_projectManagement_contextBoundary, "Project Management and Development") {
  System(mybank_projectManagement_confluence, "Projects Wiki", $descr="Platform for documenting projects.", $type="Confluence", $sprite="confluence")
  System(mybank_projectManagement_gitlab, "Development Platform", $descr="Tools for software development, testing, and deployment.", $type="GitLab")
  System(mybank_projectManagement_jira, "Project Management Tool", $descr="Platform for planning, executing, and tracking projects.", $type="Jira", $sprite="jira")
}
Person(mybank_projectManagement_projectManager, "Project Manager", $descr="Manages projects at MyBank")
Person(mybank_projectManagement_devopsEngineer, "DevOps Engineer", $descr="Develops and operates software systems")
Person(mybank_projectManagement_incidentManager, "Incident Manager", $descr="Manages incidents")
Person(mybank_projectManagement_qualityManager, "Quality Manager", $descr="Responsible for quality assurance and compliance to quality standards")
Person(mybank_projectManagement_agilityMaster, "Agility Master", $descr="Facilitates agile practices")
SHOW_LEGEND()
@enduml
