
@startwbs
* My Bank
** Projects
** Compliance & Risk Management
*** Risk Management
*** Fraud
*** Regulations
** Personal Customers
*** Mortgage
*** Internet Banking
*** Personal Loans
** IT Management
*** Azure Platform
*** AWS Platform
** Investments
*** Asset Management
** Corporate Customers
*** Loans
** Human Resources
*** Recruiting
** Marketing

@endwbs

