@startuml component-view
!include <C4/C4_Component.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>


LAYOUT_TOP_DOWN()




title Component View of the Digital Banking Systems
Boundary(mybank_digitalBanking_contextBoundary, "Digital Banking") {
  System_Boundary(mybank_digitalBanking_internetBankingSystem, "Internet Banking System") {
    Container(mybank_digitalBanking_mobileApp, "Mobile App", $descr="Provides limited internet banking functionality to customers via mobile devices.", $techn="ClojureScript and Reagent")
    Container(mybank_digitalBanking_webApp, "Web Application", $descr="Delivers the static content and the internet banking single-page application.", $techn="Clojure and Luminus")
    ContainerDb(mybank_digitalBanking_database, "Database", $descr="Stores user registration, authentication, and access logs.", $techn="Datomic")
    Container_Boundary(mybank_digitalBanking_apiApplication, "API Application") {
      Component(mybank_digitalBanking_resetPasswordController, "Reset Password Controller", $descr="Allows users to reset their passwords.", $techn="Clojure namespace")
      Component(mybank_digitalBanking_accountsSummaryController, "Accounts Summary Controller", $descr="Provides customers with a summary of their bank accounts.", $techn="Clojure namespace")
      Component(mybank_digitalBanking_signInController, "Sign In Controller", $descr="Allows users to sign in to the banking system.", $techn="Clojure namespace")
      Component(mybank_digitalBanking_coreBankingSystemsFacade, "Core Banking Systems Facade", $descr="Facilitates interaction with the core banking systems.", $techn="Clojure Namespace, http-client")
      Component(mybank_digitalBanking_securityComponent, "Security Component", $descr="Handles authentication, password changes, etc.", $techn="Clojure namespace")
      Component(mybank_digitalBanking_emailComponent, "E-mail Component", $descr="Sends e-mails to users.", $techn="Clojure namespace")
    }
    Container(mybank_digitalBanking_singlePageApp, "Single-Page Application", $descr="Provides internet banking functionality to customers via their web browser.", $techn="ClojureScript and Re-Frame")
  }
  System(mybank_digitalBanking_digitalWalletsSystem, "Digital Wallets", $descr="Supports digital wallet integration and mobile payments.", $type="Node.js and Express")
}
Rel(mybank_digitalBanking_accountsSummaryController, mybank_digitalBanking_coreBankingSystemsFacade, "retrieves account data from")
Rel(mybank_digitalBanking_resetPasswordController, mybank_digitalBanking_emailComponent, "uses for sending password reset emails")
Rel(mybank_digitalBanking_signInController, mybank_digitalBanking_securityComponent, "uses")
Rel(mybank_digitalBanking_singlePageApp, mybank_digitalBanking_signInController, "makes API calls to", $techn="Transit/HTTPS")
Rel(mybank_digitalBanking_singlePageApp, mybank_digitalBanking_accountsSummaryController, "makes API calls to", $techn="Transit/HTTPS")
Rel(mybank_digitalBanking_singlePageApp, mybank_digitalBanking_resetPasswordController, "makes API calls to", $techn="Transit/HTTPS")
SHOW_LEGEND()
@enduml
