@startuml context-view
!include <C4/C4_Context.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/java>
!include <logos/kafka>
!include <tupadr3/devicons2/cplusplus>







title Context View of the Core Banking Systems
Boundary(mybank_coreBanking_contextBoundary, "Core Banking System") {
  System(mybank_coreBanking_transactionProcessingSystem, "Transaction Processing", $descr="Processes financial transactions in real-time.", $type="Java, Kafka", $sprite="java")
  System(mybank_coreBanking_loanManagementSystem, "Loan Management", $descr="Manages loan products, applications, and repayments.", $type="Java, Spring Boot", $sprite="java")
  System(mybank_coreBanking_accountManagementSystem, "Account Management", $descr="Handles customer accounts, deposits, and withdrawals.", $type="Java, Spring Boot", $sprite="java")
}
System(mybank_payment_paymentGatewaySystem, "Payment Gateway", $descr="Facilitates credit/debit card transactions.", $type="Java, Spring Boot", $sprite="java")
System(mybank_compliance_riskManagementSystem, "Risk Management System", $descr="Detects risks and manages risk mitigation.", $type="Java, Spring Boot", $sprite="java")
System(mybank_digitalBanking_internetBankingSystem_internetBankingSystem, "Internet Banking System", $descr="Allows customers to view information about their bank accounts and make payments.")
System(mybank_customerChannels_atm, "ATM", $descr="Allows customers to withdraw cash.", $type="C++, Java", $sprite="cplusplus")
Person(mybank_coreBanking_backofficeStaff, "Backoffice Staff", $descr="Administration and support staff within the bank.")
Rel(mybank_payment_paymentGatewaySystem, mybank_coreBanking_transactionProcessingSystem, "validates and processes payments using")
Rel(mybank_customerChannels_atm, mybank_coreBanking_accountManagementSystem, "retrieves account balance")
Rel(mybank_coreBanking_loanManagementSystem, mybank_coreBanking_accountManagementSystem, "retrieves customer account information from")
Rel(mybank_customerChannels_atm, mybank_coreBanking_transactionProcessingSystem, "validates transaction")
Rel(mybank_digitalBanking_internetBankingSystem_internetBankingSystem, mybank_coreBanking_loanManagementSystem, "fetches loan details and payment status from")
Rel(mybank_digitalBanking_internetBankingSystem_internetBankingSystem, mybank_coreBanking_accountManagementSystem, "gets account information from, and makes payments using")
Rel(mybank_coreBanking_backofficeStaff, mybank_coreBanking_loanManagementSystem, "processes loan applications and updates loan status using")
Rel(mybank_compliance_riskManagementSystem, mybank_coreBanking_transactionProcessingSystem, "fetches transaction history and customer data from")
SHOW_LEGEND()
@enduml
