@startuml component-view
!include <C4/C4_Component.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>







title Component View of the Internet Banking System
System_Boundary(mybank_digitalBanking_internetBankingSystem_internetBankingSystem, "Internet Banking System") {
  Container_Boundary(mybank_digitalBanking_internetBankingSystem_apiApplication, "API Application") {
    Component(mybank_digitalBanking_internetBankingSystem_securityComponent, "Security Component", $descr="Handles authentication, password changes, etc.", $techn="Clojure namespace")
    Component(mybank_digitalBanking_internetBankingSystem_resetPasswordController, "Reset Password Controller", $descr="Allows users to reset their passwords.", $techn="Clojure namespace")
    Component(mybank_digitalBanking_internetBankingSystem_emailComponent, "E-mail Component", $descr="Sends e-mails to users.", $techn="Clojure namespace")
    Component(mybank_digitalBanking_internetBankingSystem_coreBankingSystemsFacade, "Core Banking Systems Facade", $descr="Facilitates interaction with the core banking systems.", $techn="Clojure Namespace, http-client")
    Component(mybank_digitalBanking_internetBankingSystem_accountsSummaryController, "Accounts Summary Controller", $descr="Provides customers with a summary of their bank accounts.", $techn="Clojure namespace")
    Component(mybank_digitalBanking_internetBankingSystem_signInController, "Sign In Controller", $descr="Allows users to sign in to the banking system.", $techn="Clojure namespace")
  }
  Container(mybank_digitalBanking_internetBankingSystem_singlePageApp, "Single-Page Application", $descr="Provides internet banking functionality to customers via their web browser.", $techn="ClojureScript and Re-Frame")
  Container(mybank_digitalBanking_internetBankingSystem_webApp, "Web Application", $descr="Delivers the static content and the internet banking single-page application.", $techn="Clojure and Luminus")
  Container(mybank_digitalBanking_internetBankingSystem_mobileApp, "Mobile App", $descr="Provides limited internet banking functionality to customers via mobile devices.", $techn="ClojureScript and Reagent")
  ContainerDb(mybank_digitalBanking_internetBankingSystem_database, "Database", $descr="Stores user registration, authentication, and access logs.", $techn="Datomic")
}
Person_Ext(mybank_personalCustomer, "Personal Customer", $descr="Personal Customer of MyBank.")
Rel(mybank_digitalBanking_internetBankingSystem_accountsSummaryController, mybank_digitalBanking_internetBankingSystem_coreBankingSystemsFacade, "retrieves account data from")
Rel(mybank_personalCustomer, mybank_digitalBanking_internetBankingSystem_singlePageApp, "views account balances and makes payments using")
Rel(mybank_digitalBanking_internetBankingSystem_resetPasswordController, mybank_digitalBanking_internetBankingSystem_emailComponent, "uses for sending password reset emails")
Rel(mybank_personalCustomer, mybank_digitalBanking_internetBankingSystem_webApp, "visits mybank.com via browser", $techn="HTTPS")
Rel(mybank_digitalBanking_internetBankingSystem_signInController, mybank_digitalBanking_internetBankingSystem_securityComponent, "uses")
Rel(mybank_digitalBanking_internetBankingSystem_singlePageApp, mybank_digitalBanking_internetBankingSystem_accountsSummaryController, "makes API calls to", $techn="Transit/HTTPS")
Rel(mybank_digitalBanking_internetBankingSystem_singlePageApp, mybank_digitalBanking_internetBankingSystem_resetPasswordController, "makes API calls to", $techn="Transit/HTTPS")
Rel(mybank_personalCustomer, mybank_digitalBanking_internetBankingSystem_mobileApp, "views account balances and makes payments using")
Rel(mybank_digitalBanking_internetBankingSystem_singlePageApp, mybank_digitalBanking_internetBankingSystem_signInController, "makes API calls to", $techn="Transit/HTTPS")
SHOW_LEGEND()
@enduml
