@startuml container-view
!include <C4/C4_Container.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>


LAYOUT_TOP_DOWN()




title Container View of the IT Management Systems
Person(mybank_itManagement_cloudFinopsSpecialist, "Cloud FinOps Specialist", $descr="Operates cloud infrastructure and controls costs")
Boundary(mybank_itManagement_contextBoundary, "IT Management") {
  System(mybank_infrastructureManagement_itInfrastructureSystem, "IT Infrastructure", $descr="Hardware and software resources, including servers and networking.", $type="VMware, Cisco")
  System(mybank_infrastructureManagement_cloudServicesSystem, "Cloud Services", $descr="Cloud computing resources for scalability and flexibility.", $type="AWS, Azure")
  System(mybank_infrastructureManagement_systemMonitoringSystem, "System Monitoring", $descr="Monitors system performance and health.", $type="Nagios, Prometheus")
}
Person(mybank_itManagement_cloudOperationsSpecialist, "Cloud Operations Specialist", $descr="Operates cloud infrastructure")
Person(mybank_itManagement_itManager, "IT Manager", $descr="Manages the IT platform")
Person(mybank_itManagement_cloudSolutionArchitect, "Cloud Solution Architect", $descr="Designs cloud solutions")
Person(mybank_itManagement_databaseAdministrator, "Database Administrator", $descr="Manages databases")
Person(mybank_itManagement_securityEngineer, "Security Engineer", $descr="Designs and operates security infrastructure")
Person(mybank_itManagement_networkEngineer, "Network Engineer", $descr="Designs and operates network infrastructure")
SHOW_LEGEND()
@enduml
