@startuml container-view
!include <C4/C4_Container.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>


LAYOUT_TOP_DOWN()




title Container View of the IT Management Systems
Person(mybank_itManagement_cloudFinopsSpecialist, "Cloud FinOps Specialist", $descr="Operates cloud infrastructure and controls costs")
Person(mybank_itManagement_cloudOperationsSpecialist, "Cloud Operations Specialist", $descr="Operates cloud infrastructure")
Person(mybank_itManagement_cloudSolutionArchitect, "Cloud Solution Architect", $descr="Designs cloud solutions")
Person(mybank_itManagement_databaseAdministrator, "Database Administrator", $descr="Manages databases")
Person(mybank_itManagement_securityEngineer, "Security Engineer", $descr="Designs and operates security infrastructure")
Person(mybank_itManagement_networkEngineer, "Network Engineer", $descr="Designs and operates network infrastructure")
SHOW_LEGEND()
@enduml
