@startuml deployment-view
!include <C4/C4_Deployment.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>
!include <azure/Networking/AzureExpressRoute>
!include <azure/Networking/AzureVirtualNetworkPeering>


LAYOUT_TOP_DOWN()




title Deployment View of the IT Management Systems
Rel(mybank_itManagement_azure_lz1Vnet1, mybank_itManagement_azure_hubVnet, "peered to", $descr="Provides connectivity for the spoke", $techn="Azure Virtual Network Peering", $sprite="AzureVirtualNetworkPeering,scale=0.5")
Rel(mybank_itManagement_onprem_dataCenter, mybank_itManagement_azure_hubVnet, "network link", $descr="High speed/volume link 100 Mb/s", $techn="Azure Express Route", $sprite="AzureExpressRoute,scale=0.5")
SHOW_LEGEND()
@enduml
