@startuml context-view
!include <C4/C4_Context.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>


LAYOUT_TOP_DOWN()




title Context View of the Compliance and Risk Management Systems
SHOW_LEGEND()
@enduml
