@startuml container-view
!include <C4/C4_Container.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>


LAYOUT_TOP_DOWN()




title Container View of the Compliance and Risk Management Systems
Person(mybank_compliance_riskManager, "Risk Manager", $descr="Responsible for managing the risks.")
Boundary(mybank_compliance_contextBoundary, "Risk Management and Compliance") {
  System(mybank_compliance_riskManagementSystem, "Risk Management System", $descr="Detects risks and manages risk mitigation.", $type="Java, Spring Boot")
  System(mybank_compliance_fraudDetectionSystem, "Fraud Detection System", $descr="Detects and mitigates fraudulent activities.", $type="Python, TensorFlow")
  System(mybank_compliance_amlSystem, "Anti-Money Laundering (AML) System", $descr="Monitors and prevents money laundering activities.", $type="Python, Scikit-learn")
  System(mybank_compliance_complianceSystem, "Compliance System", $descr="Ensures operations comply with regulations.", $type="Java, Spring Boot")
}
Person(mybank_compliance_fraudSpecialist, "Fraud specialist", $descr="Responsible for the fraud detection and mitigation of MyBank.")
Person(mybank_compliance_complianceManager, "Compliance Manager", $descr="Responsible for the compliance of MyBank.")
SHOW_LEGEND()
@enduml
